name: Unit Test Check
on: pull_request

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get base branch dynamically
        run: echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Fetch latest changes
        run: git fetch origin $BASE_BRANCH

      - name: Check .cs file changes and apply rules
        run: |
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD)
          
          # Ignore specific directories
          IGNORED_PATHS_REGEX='^x/hdhd/|^y/hdish/'

          # Added .cs files (excluding ignored paths)
          ADDED_CS=$(git diff --name-only --diff-filter=A origin/$BASE_BRANCH...HEAD | grep -iE '\.cs$' | grep -vE "$IGNORED_PATHS_REGEX" || true)
          ADDED_TEST_CS=$(echo "$ADDED_CS" | grep -iE 'test.*\.cs$' || true)
          NON_TEST_ADDED_CS=$(echo "$ADDED_CS" | grep -viE 'test.*\.cs$' || true)

          # Modified .cs files (excluding ignored paths)
          MODIFIED_CS=$(git diff --name-only --diff-filter=M origin/$BASE_BRANCH...HEAD | grep -iE '\.cs$' | grep -vE "$IGNORED_PATHS_REGEX" || true)
          MODIFIED_TEST_CS=$(echo "$MODIFIED_CS" | grep -iE 'test.*\.cs$' || true)

          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo "Added .cs files:"
          echo "$ADDED_CS"
          echo "Modified .cs files:"
          echo "$MODIFIED_CS"
          echo "Added test files:"
          echo "$ADDED_TEST_CS"
          echo "Modified test files:"
          echo "$MODIFIED_TEST_CS"

          # Check if there are any .cs changes outside ignored paths
          if [ -z "$ADDED_CS" ] && [ -z "$MODIFIED_CS" ]; then
            echo "✅ Only ignored paths changed or no .cs changes. Skipping further checks."
            exit 0
          fi

          # Rule: New .cs files added, but no test file added => error
          if [ -n "$NON_TEST_ADDED_CS" ] && [ -z "$ADDED_TEST_CS" ]; then
            echo "❌ Error: New non-test .cs files were added without test files:"
            echo "$NON_TEST_ADDED_CS"
            exit 1
          fi

          # Rule: 5+ .cs files modified, and no test changed => error
          MODIFIED_COUNT=$(echo "$MODIFIED_CS" | grep -c '^' || true)
          if
